### ISSUE TITLE
Not working anymore 2nd :-/

### ISSUE THREAD

**Issue by Alfons-Hetler** [Sorrow446/PS4-OPKG-Update-Downloader#3]
Hey man,
if i start i get the following error...

Input CUSA: CUSA18534
Traceback (most recent call last):
  File "C:\Users\Computer\Desktop\PS4\PS4_Spiele_Update_Downloader\ps4_opkg_update_downloader.py", line 55, in parse_meta
    game_title = soup.find('h3', {'class': 'h3-title'}).text.strip()
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Computer\Desktop\PS4\PS4_Spiele_Update_Downloader\ps4_opkg_update_downloader.py", line 181, in <module>
    main(cusa)
  File "C:\Users\Computer\Desktop\PS4\PS4_Spiele_Update_Downloader\ps4_opkg_update_downloader.py", line 138, in main
    parsed_meta = parse_meta(html)
  File "C:\Users\Computer\Desktop\PS4\PS4_Spiele_Update_Downloader\ps4_opkg_update_downloader.py", line 57, in parse_meta
    raise Exception('Couldn\'t find any updates for specified CUSA.')
Exception: Couldn't find any updates for specified CUSA.
Press enter to exit.

pls fix it i like the tool very...

Thanks man

**Comment by Sorrow446** [comment]
This is an old tool and it doesn't work anymore. I've been considering rewriting it; I'll keep you updated.

**Comment by cyber-speed** [comment]
Hi,

Any news on the update, i get same error output :)
